{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"fail()","externalID":"s:10ConsoleKit17ActivityIndicatorC4failyyF","modules":[{"name":"ConsoleKit"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit","doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"()"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"Passes ","type":"text"},{"code":"ActivityIndicatorState.failure","type":"codeVoice"},{"text":" to the ","type":"text"},{"code":"ActivityIndicatorType","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Must be called after ","type":"text"},{"type":"codeVoice","code":"start(on:)"},{"text":" and completes the future returned by that method.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Stops the "},{"type":"codeVoice","code":"ActivityIndicator"},{"type":"text","text":", yielding a failed \/ error appearance."}],"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator\/fail()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/consolekit\/activityindicator\/fail()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/ConsoleKit":{"kind":"symbol","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit","url":"\/documentation\/consolekit","role":"collection","title":"ConsoleKit","abstract":[]},"doc://co.pointfree.VaporRouting/documentation/ConsoleKit/ActivityIndicator":{"navigatorTitle":[{"text":"ActivityIndicator","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityIndicator","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An instance of a "},{"type":"codeVoice","code":"ActivityIndicatorType"},{"text":" that can be started, failed, and succeeded.","type":"text"}],"url":"\/documentation\/consolekit\/activityindicator","title":"ActivityIndicator"},"doc://co.pointfree.VaporRouting/documentation/ConsoleKit/ActivityIndicator/fail()":{"type":"topic","title":"fail()","role":"symbol","kind":"symbol","url":"\/documentation\/consolekit\/activityindicator\/fail()","abstract":[{"text":"Stops the ","type":"text"},{"type":"codeVoice","code":"ActivityIndicator"},{"type":"text","text":", yielding a failed \/ error appearance."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator\/fail()"}}}