{"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":", "},{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","preciseIdentifier":"s:7NIOCore10ByteBufferV","kind":"typeIdentifier","text":"ByteBuffer"},{"kind":"text","text":")"}],"platforms":["Linux"]}]}],"abstract":[{"type":"text","text":"More data has been received by a "},{"code":"ByteToMessageHandler","type":"codeVoice"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"code":"Error","type":"codeVoice"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"NIOCore"}],"role":"symbol","title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:7NIOCore25ByteToMessageDecoderErrorO014dataReceivedInF5StateyACs0F0_p_AA0B6BufferVtcACmF","roleHeading":"Case"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError"]]},"sections":[],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOCore":{"title":"NIOCore","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore","abstract":[],"url":"\/documentation\/niocore","type":"topic","kind":"symbol","role":"collection"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError","title":"ByteToMessageDecoderError","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteToMessageDecoderError"}],"navigatorTitle":[{"kind":"identifier","text":"ByteToMessageDecoderError"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror","abstract":[{"type":"text","text":"Common errors thrown by "},{"type":"codeVoice","code":"ByteToMessageDecoder"},{"type":"text","text":"s."}]},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteBuffer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ByteBuffer"}],"navigatorTitle":[{"kind":"identifier","text":"ByteBuffer"}],"title":"ByteBuffer","type":"topic","abstract":[{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" stores contiguously allocated raw bytes. It is a random and sequential accessible sequence of zero or"},{"type":"text","text":" "},{"type":"text","text":"more bytes (octets)."}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteBuffer","role":"symbol","url":"\/documentation\/niocore\/bytebuffer","kind":"symbol"},"doc://co.pointfree.VaporRouting/documentation/NIOCore/ByteToMessageDecoderError/dataReceivedInErrorState(_:_:)":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOCore\/ByteToMessageDecoderError\/dataReceivedInErrorState(_:_:)","title":"ByteToMessageDecoderError.dataReceivedInErrorState(_:_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataReceivedInErrorState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:7NIOCore10ByteBufferV","text":"ByteBuffer"},{"kind":"text","text":")"}],"url":"\/documentation\/niocore\/bytetomessagedecodererror\/datareceivedinerrorstate(_:_:)","abstract":[{"type":"text","text":"More data has been received by a "},{"type":"codeVoice","code":"ByteToMessageHandler"},{"type":"text","text":" despite the fact that an error has previously been"},{"type":"text","text":" "},{"type":"text","text":"emitted. The associated "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" is the error previously emitted and the "},{"type":"codeVoice","code":"ByteBuffer"},{"type":"text","text":" is the extra data that has"},{"type":"text","text":" "},{"type":"text","text":"been received. The common cause for this error to be emitted is the user not having torn down the "},{"type":"codeVoice","code":"Channel"},{"type":"text","text":" "},{"type":"text","text":"after previously an "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" has been sent through the pipeline using "},{"type":"codeVoice","code":"fireErrorCaught"},{"type":"text","text":"."}]}}}